server:
  port: 8080
spring:
  resources:
    static-locations: ["classpath:/static/"]
  datasource:
    driver-class-name: 
    username: 
    password: 
    url: 
    platform: 
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false